"""WAF detection.

Detection combines two signals:

1. **Signatures** - vendor-specific fingerprints in response headers, cookies
   and body text (Cloudflare, Akamai, AWS, Imperva, F5, ModSecurity, ...).
2. **Behaviour** - send a benign request and a deliberately hostile one; if the
   hostile one is blocked (status change, block markers, big response delta)
   while the benign one succeeds, a filter is present even without a signature.
"""

from __future__ import annotations

import re
from typing import List, Optional

from .engine import Engine, Response
from .models import Outcome, WAFFingerprint
from .target import Target

# vendor -> list of (where, regex). where in {"header", "cookie", "body"}
_SIGNATURES = {
    "Cloudflare": [
        ("header", re.compile(r"cf-ray|__cfduid|cf-cache-status", re.I)),
        ("header", re.compile(r"server:\s*cloudflare", re.I)),
        ("body", re.compile(r"attention required.*cloudflare", re.I)),
    ],
    "Akamai": [
        ("header", re.compile(r"akamai|x-akamai", re.I)),
        ("cookie", re.compile(r"ak_bmsc|bm_sz", re.I)),
        ("body", re.compile(r"reference #\d+\.\w+", re.I)),
    ],
    "AWS WAF": [
        ("header", re.compile(r"x-amzn-|x-amz-cf-id|awselb", re.I)),
        ("body", re.compile(r"request blocked", re.I)),
    ],
    "Imperva/Incapsula": [
        ("header", re.compile(r"x-iinfo|incap_ses|visid_incap", re.I)),
        ("cookie", re.compile(r"incap_ses|visid_incap", re.I)),
        ("body", re.compile(r"incapsula incident id", re.I)),
    ],
    "F5 BIG-IP ASM": [
        ("header", re.compile(r"x-cnection|bigipserver|ts[0-9a-f]{8}", re.I)),
        ("cookie", re.compile(r"^ts[0-9a-f]+", re.I)),
        ("body", re.compile(r"the requested url was rejected", re.I)),
    ],
    "ModSecurity": [
        ("header", re.compile(r"mod_security|modsecurity", re.I)),
        ("body", re.compile(r"mod_security|not acceptable", re.I)),
    ],
    "Sucuri": [
        ("header", re.compile(r"x-sucuri-id|x-sucuri-cache", re.I)),
        ("body", re.compile(r"sucuri website firewall", re.I)),
    ],
    "Wordfence": [
        ("body", re.compile(r"generated by wordfence", re.I)),
    ],
    "Barracuda": [
        ("cookie", re.compile(r"barra_counter_session", re.I)),
        ("body", re.compile(r"barracuda", re.I)),
    ],
    "FortiWeb": [
        ("cookie", re.compile(r"fortiwafsid", re.I)),
        ("body", re.compile(r"fortiweb", re.I)),
    ],
}

# Loud payloads designed to trip filters without harming the target.
_PROBES = [
    "' OR 1=1-- -",
    "' UNION SELECT NULL-- -",
    "<script>alert(1)</script>",
    "../../../../etc/passwd",
    "1 AND SLEEP(0)",
]


class WAFDetector:
    def __init__(self, engine: Engine) -> None:
        self.engine = engine

    def detect(self, target: Target) -> WAFFingerprint:
        fp = WAFFingerprint()

        baseline = self.engine.send(target.baseline())
        self._match_signatures(baseline, fp)

        # Behavioural probing.
        blocked_probes = 0
        for probe in _PROBES:
            point = target.injection_points()[0] if target.injection_points() else None
            if point is None:
                break
            resp = self.engine.send(target.build(point, probe))
            self._match_signatures(resp, fp)
            if self._looks_blocked(baseline, resp):
                blocked_probes += 1

        if blocked_probes:
            fp.detected = True
            ratio = blocked_probes / len(_PROBES)
            fp.confidence = max(fp.confidence, min(0.5 + ratio / 2, 0.99))
            fp.evidence.append(
                f"{blocked_probes}/{len(_PROBES)} hostile probes were blocked"
            )

        if fp.vendor and not fp.detected:
            # A signature alone still means a WAF is in front of the app.
            fp.detected = True
            fp.confidence = max(fp.confidence, 0.7)

        return fp

    # ------------------------------------------------------------------ #
    def _match_signatures(self, resp: Response, fp: WAFFingerprint) -> None:
        header_blob = "\n".join(f"{k}: {v}" for k, v in resp.headers.items())
        cookie_blob = resp.headers.get("set-cookie", "")
        body = resp.text[:20000]

        for vendor, sigs in _SIGNATURES.items():
            for where, rx in sigs:
                hay = {"header": header_blob, "cookie": cookie_blob, "body": body}[where]
                if rx.search(hay):
                    if fp.vendor is None:
                        fp.vendor = vendor
                    ev = f"{vendor}: matched /{rx.pattern}/ in {where}"
                    if ev not in fp.evidence:
                        fp.evidence.append(ev)
                    fp.confidence = max(fp.confidence, 0.8)

    @staticmethod
    def _looks_blocked(baseline: Response, probe: Response) -> bool:
        if probe.outcome in (Outcome.BLOCKED, Outcome.RATE_LIMITED):
            return True
        if baseline.status_code and probe.status_code:
            # A hostile probe that flips a 200 into a 4xx is a strong signal.
            if baseline.status_code < 400 <= probe.status_code:
                return True
        return False
